// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("4bff9703-28a5-46a6-995b-7db22406e3d0")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("SiUnits.Tests")]
